# Generated by Django 4.2 on 2023-05-15 15:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userchoice",
            name="choice",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
